export default {
    /** @type {number} */
    TILE_SIZE: 32,
    TILE_MIDLE_SIZE: 16,
    MOVE_DURATION: 80,
    RANGED_ATTACK_DURATION: 10,
    MELEE_ATTACK_DURATION: 80,
    DIE_DURATION: 10,
    COLOR_SELECTION: 0xffff00,
    COLOR_SELECTION_ERROR: 0x760223,


    COLOR_BUTTON_BACKGROUND: 0x7b5e57,

    SPRITESHEET_MAP_1: "ground1",
    SPRITESHEET_ACTORS: "monsters1",
    SPRITESHEET_ICONS: "icons1"
}