export default {
    /** @type {number} */
    TILE_SIZE: 16,
    TILE_MIDLE_SIZE: 8,
    MOVE_DURATION: 10,
    RANGED_ATTACK_DURATION: 40,
    MELEE_ATTACK_DURATION: 40,
    DIE_DURATION: 30,
    COLOR_SELECTION: 0xffff00,
    COLOR_SELECTION_ERROR: 0x760223,
    MOVE_SPEED: 1000
}