export default {
    /** @type {number} */
    TILE_SIZE: 32,
    TILE_MIDLE_SIZE: 16,
    MOVE_DURATION: 50,
    RANGED_ATTACK_DURATION: 40,
    MELEE_ATTACK_DURATION: 40,
    DIE_DURATION: 30,
    COLOR_SELECTION: 0xffff00,
    COLOR_SELECTION_ERROR: 0x760223
}